### PR TITLE
Design of a hero section for the website.

### PR DESCRIPTION
**Pull request by antidotejack**
Hi, I'm Jack and this is my first contribution to an open source project. I hope you like this idea for a hero section.

### CODE REVIEW

**Comment by Alecaddd** [comment]
Hi, thanks for the contribution.
Nice little design.
I actually have a repository for the website, but I never got the time to create one. https://github.com/akiraux/website

**Comment by antidotejack** [comment]
Can I start building the website?

**Comment by Alecaddd** [comment]
Sure, just pure html css and javascript

**Comment by antidotejack** [comment]
I can't be more pleased! Thanks Alessandro.

**Pull request merged**
